### ISSUE TITLE
Receiving error on import of containeranalysis 2.0.0

### ISSUE THREAD

**Issue by G-Goldstein** [googleapis/python-containeranalysis#38]
I've been following some examples for how to use this client and I'm falling at the first hurdle: Importing the containeranalysis package results in an error! Please find below my steps to reproduce, starting from a new virtualenv on Python3.6.8:

```
(env) [ggoldstein@vmtool attestations]$ pip --version
pip 20.2.1 from /home/ggoldstein/attestations/env/lib/python3.6/site-packages/pip (python 3.6)
(env) [ggoldstein@vmtool attestations]$ python --version
Python 3.6.8
(env) [ggoldstein@vmtool attestations]$ pip freeze
(env) [ggoldstein@vmtool attestations]$ pip install google-cloud-containeranalysis

[... snip ...]

(env) [ggoldstein@vmtool attestations]$ pip freeze
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
dataclasses==0.7
google-api-core==1.22.1
google-auth==1.20.1
google-cloud-containeranalysis==2.0.0
googleapis-common-protos==1.52.0
grafeas==1.0.1
grpc-google-iam-v1==0.12.3
grpcio==1.31.0
idna==2.10
libcst==0.3.9
mypy-extensions==0.4.3
proto-plus==1.7.0
protobuf==3.12.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pytz==2020.1
PyYAML==5.3.1
requests==2.24.0
rsa==4.6
six==1.15.0
typing-extensions==3.7.4.2
typing-inspect==0.6.0
urllib3==1.25.10
(env) [ggoldstein@vmtool attestations]$ python -c "from google.cloud.devtools import containeranalysis_v1"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/cloud/devtools/containeranalysis_v1/__init__.py", line 18, in <module>
    from .services.container_analysis import ContainerAnalysisClient
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/cloud/devtools/containeranalysis_v1/services/container_analysis/__init__.py", line 18, in <module>
    from .client import ContainerAnalysisClient
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/cloud/devtools/containeranalysis_v1/services/container_analysis/client.py", line 26, in <module>
    from google.api_core import gapic_v1  # type: ignore
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/api_core/gapic_v1/__init__.py", line 19, in <module>
    from google.api_core.gapic_v1 import method
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/api_core/gapic_v1/method.py", line 22, in <module>
    from google.api_core import grpc_helpers
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 27, in <module>
    import google.auth.transport.requests
  File "/home/ggoldstein/attestations/env/lib/python3.6/site-packages/google/auth/transport/requests.py", line 36, in <module>
    import requests.adapters  # pylint: disable=ungrouped-imports
ModuleNotFoundError: No module named 'requests.adapters'; 'requests' is not a package
```

This import line I'm using appears in several of the example code snippets so I'm not expecting it to fall over so soon. I'm running this on CentOS Linux release 7.8.2003 (Core). I've previously imported other google.cloud packages in different virtualenvs without incident.

**Comment by G-Goldstein** [comment]
I seem to get the same issue if I uninstall everything in pip and specify google-cloud-containeranalysis==1.0.3 on the install, so I don't think this is new to me in 2.0.0.

**Comment by G-Goldstein** [comment]
It turns out this was my fault, as I had a `requests.py` file in the same directory as the command I was executing. Once this file was moved/renamed, the module works.
